language: ruby
cache: bundler
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
install:
  - bundle exec gem install rake -v 10.5
  - bindle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
script: bundle exec rake
